spring:
  profiles:
    active: development

logging:
  level:
    root: INFO

management.endpoints.web.exposure.include: "*"
management.endpoints.jmx.exposure.exclude: "*"
---
spring:
  profiles: development
logging:
  level:
    root: DEBUG
---
spring:
  profiles: production
logging:
  level:
    root: INFO





