spring:
  profiles:
    active: development

logging:
  level:
    root: INFO

---
spring:
  profiles: development
logging:
  level:
    root: DEBUG
---
spring:
  profiles: production
logging:
  level:
    root: INFO





